server:
  port: 8080
spring:
  data:
    mongodb:
      host:  mongodb-sdhub
      port: 27017
      database: sdhub-mongo
app:
  build:
    version: ^project.version^
  sdhubId: BPNL000000000000
  custodianWallet:
    uri: https://custodian-dev.germanywestcentral.cloudapp.azure.com/api
    auth-server-url: https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth
    realm: CX-Central
    clientId:
    clientSecret:
    username:
    password:
  db:
    sd:
      collectionName: selfdescription
