spring:
  data:
    mongodb:
      host:  mongo
      port: 27017
      database: sdhub-mongo
keycloak:
  auth-server-url: https://catenaxdev003akssrv.germanywestcentral.cloudapp.azure.com/iamcentralidp/auth
  realm: CX-Central
app:
  build:
    version: ^project.version^
  sdhubId: BPNL000000000000
  custodianWallet:
    uri: https://custodian-dev.germanywestcentral.cloudapp.azure.com/api
    clientId: Client005-CustodianTest
    clientSecret: Htv9MhV2rk6XM9zV54xdo2cwSMxFIBzU
    username: custodian@catenax.de
    password: changeme
  db:
    sd:
      collectionName: selfdescription4
