openapi: 3.0.0
info:
  version: 1.0.6
  title: SD-Factory API
  description: API for creating and storing the Verifiable Credentials

paths:
  /selfdescription:
    post:
      summary: Creates a Verifiable Credential and returns it
      operationId: selfdescriptionPost
      requestBody:
        required: true
        description: parameters to generate VC
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LegalPersonSchema'
                - $ref: '#/components/schemas/ServiceOfferingSchema'
                - $ref: '#/components/schemas/TermsAndConditionsSchema'
                - $ref: '#/components/schemas/PhysicalResourceSchema'
                - $ref: '#/components/schemas/VirtualResourceSchema'
                - $ref: '#/components/schemas/InstantiatedVirtualResourceSchema'
              discriminator:
                propertyName: type
                mapping:
                  LegalPerson: '#/components/schemas/LegalPersonSchema'
                  ServiceOffering: '#/components/schemas/ServiceOfferingSchema'
                  TermsAndConditions: '#/components/schemas/TermsAndConditionsSchema'
                  PhysicalResource: '#/components/schemas/PhysicalResourceSchema'
                  VirtualResource: '#/components/schemas/VirtualResourceSchema'
                  InstantiatedVirtualResource: '#/components/schemas/InstantiatedVirtualResourceSchema'
            examples:
              LegalPerson:
                description: payload to create LegalPerson
                value:
                  type: LegalPerson
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  registrationNumber: o12345678
                  headquarterAddress.country: DE
                  legalAddress.country: DE
                  leiCode: <20 digit alphanumeric code>
                  parentOrganisation: [
                    https://<link_to_parent_organisation>,
                    https://<link_to_parent_organisation>
                  ]
                  subOrganisation: [
                    https://<link_to_parent_suborganisation>,
                    https://<link_to_parent_suborganisation>
                  ]
                  bpn: BPNL000000000000
              ServiceOffering:
                description: payload to create ServiceOffering
                value:
                  type: ServiceOffering
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  providedBy: https://<link_to_participant>
                  aggregationOf: [
                    https://<link_to_resource_SD>,
                    https://<link_to_resource_SD>
                  ]
                  termsAndConditions: [
                    {
                      URL: https://<link_to_terms_and_conditions>,
                      hash: <sha256 hash of the document>
                    },
                    {
                      URL: https://<link_to_terms_and_conditions>,
                      hash: <sha256 hash of the document>
                    }
                  ]
                  policies: [
                    Policy example,
                    Policy example
                  ]
              PhysicalResource:
                description: payload to create PhysicalResource
                value:
                  type: PhysicalResource
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  aggregationOf: [
                    https://<link_to_resources_self_description>,
                    https://<link_to_resources_self_description>
                  ]
                  maintainedBy: [
                    https://<link_to_participant_self_description>
                  ]
                  ownedBy: [
                    https://<link_to_participant>
                  ]
                  manufacturedBy: [
                    https://<link_to_participant>
                  ]
                  locationAddress.country: [
                    DE
                  ]
                  location.gps: [
                    <GPS location in ISO 6709:2008/Cor 1:2009 format>
                  ]
              VirtualResource:
                description: payload to create VirtualResource
                value:
                  type: VirtualResource
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  aggregationOf: [
                    https://<link_to_resources_self_description>,
                    https://<link_to_resources_self_description>
                  ]
                  copyrightOwnedBy: [
                    https://<link_to_participant_self_description>
                  ]
                  license: [
                    https://<link_to_license_document>
                  ]
              InstantiatedVirtualResource:
                description: payload to create InstantiatedVirtualResource
                value:
                  type: InstantiatedVirtualResource
                  holder: BPNL000000000000
                  issuer: CAXSDUMMYCATENAZZ
                  aggregationOf: [
                    https://<link_to_resources_self_description>,
                    https://<link_to_resources_self_description>
                  ]
                  copyrightOwnedBy: [
                    https://<link_to_participant_self_description>
                  ]
                  license: [
                    https://<link_to_license_document>
                  ]
                  maintainedBy: [
                    https://<link_to_participant>
                  ]
                  hostedOn: [
                    https://<link_to_resource>
                  ]
                  tenantOwnedBy: [
                    https://<link_to_participant_self_description>
                  ]
                  endpoint: [
                    https://<exposed_endpoints>
                  ]
      responses:
        '201':
          description: Created
          content:
            application/vc+ld+json:
              schema:
                type: object
                additionalProperties: {}
              examples:
                jsonLegalPersonObject:
                  summary: A sample LegalPerson response
                  value: |
                    {
                      "id": "https://sdfactory.int.demo.catena-x.net/selfdescription/vc/1fb3ca5f-234e-4639-8e96-f2ceb56714f0",
                      "@context": [
                        "https://www.w3.org/2018/credentials/v1",
                        "https://raw.githubusercontent.com/catenax-ng/product-sd-hub/eclipse_preparation/src/main/resources/verifiablecredentials.jsonld/sd-document-v0.1.jsonld",
                        "https://w3id.org/vc/status-list/2021/v1"
                      ],
                      "type": [
                        "VerifiableCredential",
                        "LegalPerson"
                      ],
                      "issuer": "did:sov:BEumURwPdXCobgbPYQZXge",
                      "issuanceDate": "2022-10-08T18:12:14Z",
                      "expirationDate": "2023-01-06T18:12:14Z",
                      "credentialSubject": {
                        "headquarter_country": "DE",
                        "legal_country": "DE",
                        "bpn": "BPNL000000000000",
                        "registration_number": "12345678",
                        "id": "did:indy:idunion:test:P5TFvs9PQ6e6nMB18XVTJw"
                      },
                      "credentialStatus": {
                        "id": "https://managed-identity-wallets.int.demo.catena-x.net/api/credentials/status/fe5da20d-35c1-4154-b764-1e7dc875ca1d#61",
                        "type": "StatusList2021Entry",
                        "statusPurpose": "revocation",
                        "statusListIndex": "61",
                        "statusListCredential": "https://managed-identity-wallets.int.demo.catena-x.net/api/credentials/status/fe5da20d-35c1-4154-b764-1e7dc875ca1d"
                      },
                      "proof": {
                        "type": "Ed25519Signature2018",
                        "created": "2022-10-08T18:12:16Z",
                        "proofPurpose": "assertionMethod",
                        "verificationMethod": "did:sov:BEumURwPdXCobgbPYQZXge#key-1",
                        "jws": "eyJhbGciOiAiRWREU0EiLCAiYjY0IjogZmFsc2UsICJjcml0IjogWyJiNjQiXX0..PNxly7b0d714bapo58YB-qmTtw7q3TVB7plOtaQRCXF2VrCwO4-x7Fx8PeavnwYpzu8adF8ZLnALDgMuPBXIAg"
                      }
                    }
                jsonServiceOfferingObject:
                  summary: A sample ServiceOffering response
                  value: |
                    {
                        "@context": [
                            "https://www.w3.org/2018/credentials/v1",
                            "https://raw.githubusercontent.com/catenax-ng/product-sd-hub/eclipse_preparation/src/main/resources/verifiablecredentials.jsonld/sd-document-v0.1.jsonld",
                            "https://w3id.org/vc/status-list/2021/v1"
                        ],
                        "type": [
                            "VerifiableCredential",
                            "ServiceOffering"
                        ],
                        "issuer": "did:sov:BEumURwPdXCobgbPYQZXge",
                        "issuanceDate": "2022-10-08T19:10:20Z",
                        "expirationDate": "2023-01-06T19:10:20Z",
                        "credentialSubject": {
                            "termsAndConditions": "http://terms.and.cond",
                            "policies": "policies",
                            "provided_by": "sss",
                            "id": "did:indy:idunion:test:P5TFvs9PQ6e6nMB18XVTJw"
                        },
                        "credentialStatus": {
                            "id": "https://managed-identity-wallets.int.demo.catena-x.net/api/credentials/status/fe5da20d-35c1-4154-b764-1e7dc875ca1d#67",
                            "type": "StatusList2021Entry",
                            "statusPurpose": "revocation",
                            "statusListIndex": "67",
                            "statusListCredential": "https://managed-identity-wallets.int.demo.catena-x.net/api/credentials/status/fe5da20d-35c1-4154-b764-1e7dc875ca1d"
                        },
                        "proof": {
                            "type": "Ed25519Signature2018",
                            "created": "2022-10-08T19:10:23Z",
                            "proofPurpose": "assertionMethod",
                            "verificationMethod": "did:sov:BEumURwPdXCobgbPYQZXge#key-1",
                            "jws": "eyJhbGciOiAiRWREU0EiLCAiYjY0IjogZmFsc2UsICJjcml0IjogWyJiNjQiXX0..ivUytTwbtcxByw5L2zuxpE4pjJTIEzaLPoW_gXUtByjfN34ViEbgq6KeKO82ejB6GNetzJcu7sqsZfp6-GPzDA"
                        }
                    }
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    SelfDescriptionSchema:
      type: object
      description: An identifiable Self Description
      properties:
        type:
          type: string
          maxLength: 64
        holder:
          type: string
          maxLength: 128
        issuer:
          type: string
          maxLength: 128
      required:
        - type
        - holder
        - issuer
    PolicySchema:
      type: string
    AddressSchema:
      type: object
      properties:
        country:
          type: string
          description: Country code in ISO 3166-1 alpha2, alpha-3 or numeric format.
          maxLength: 12
    GpsSchema:
      type: object
      properties:
        gps:
          type: string
          description: physical GPS in ISO 6709:2008/Cor 1:2009 format
    LegalPersonSchema:
      type: object
      description: A Participant is a Legal Person
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - type: object
          properties:
            registrationNumber:
              type: string
              description: Country's registration number which identify one specific company.
            headquarterAddress:
              $ref: '#/components/schemas/AddressSchema'
            legalAddress:
              $ref: '#/components/schemas/AddressSchema'
            leiCode:
              type: string
            parentOrganisation:
              type: array
              description: A list of direct participant that this entity is a subOrganization of, if any.
              items:
                type: string
                format: uri
            subOrganisation:
              type: array
              description: A list of direct participant with an legal mandate on this entity, e.g., as a subsidiary.
              items:
                type: string
                format: uri
            bpn:
              type: string
          required:
            - registrationNumber
            - headquarterAddress
            - legalAddress
            - bpn
    ServiceOfferingSchema:
      type: object
      description: Service Offering
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - properties:
            providedBy:
              type: string
              description: a resolvable link to the participant self-description providing the service
              format: uri
            aggregationOf:
              type: array
              description: a resolvable link to the resources self-description related to the service and that can exist independently of it.
              items:
                type: string
                format: uri
            termsAndConditions:
              type: array
              description: a resolvable link to the Terms and Conditions appling to that service
              items:
                $ref: '#/components/schemas/TermsAndConditionsSchema'
            policies:
              type: array
              description: a list of policy expressed using a DSL (e.g., Rego or ODRL)
              items:
                $ref: '#/components/schemas/PolicySchema'
          required:
            - providedBy
            - termsAndConditions
    TermsAndConditionsSchema:
      type: object
      allOf:
        - type: object
          properties:
            URL:
              type: string
              description: a resolvable link to document
              format: uri
            hash:
              type: string
              description: sha256 hash of the above document.
          required:
            - URL
            - hash
    Resource:
      type: object
      properties:
        aggregationOf:
          type: array
          description: resources related to the resource and that can exist independently of it.
          items:
            type: string
            format: uri
    PhysicalResourceSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            maintainedBy:
              type: array
              description: a list of participant maintaining the resource in operational condition and thus have physical access to it.
              items:
                type: string
                format: uri
                minItems: 1
            ownedBy:
              type: array
              description: a list of participant owning the resource.
              items:
                type: string
                format: uri
            manufacturedBy:
              type: array
              description: a list of participant manufacturing the resource.
              items:
                type: string
                format: uri
            locationAddress:
              type: array
              description: a list of physical location in ISO 3166-1 alpha2, alpha-3 or numeric format.
              items:
                $ref: '#/components/schemas/AddressSchema'
            location:
              type: array
              description: a list of physical GPS in ISO 6709:2008/Cor 1:2009 format.
              items:
                $ref: '#/components/schemas/GpsSchema'
          required:
            - maintainedBy
            - locationAddress
    VirtualResourceSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - $ref: '#/components/schemas/Resource'
        - type: object
          properties:
            copyrightOwnedBy:
              type: array
              description: |
                A list of copyright owner either as a free form string or participant self-description. 
                A copyright owner is a person or organization, that has the right to exploit the resource. 
                Copyright owner does not necessary refer to the author of the resource, who is a natural 
                person and may differ from copyright owner.
              items:
                type: string
                minItems: 1
            license:
              type: array
              description: A list of SPDX license identifiers or URL to license document
              items:
                type: string
                minItems: 1
          required:
            - copyrightOwnedBy
            - license
    InstantiatedVirtualResourceSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/SelfDescriptionSchema'
        - $ref: '#/components/schemas/VirtualResourceSchema'
        - type: object
          properties:
            maintainedBy:
              type: array
              description: a list of participant maintaining the resource in operational condition.
              items:
                type: string
                format: uri
                minItems: 1
            hostedOn:
              type: string
              description: a resource where the process is running, being executed on.
              format: uri
            tenantOwnedBy:
              type: array
              description: a list of participant with contractual relation with the resource.
              items:
                type: string
                format: uri
                minItems: 1
            endpoint:
              type: array
              description: a list of exposed endpoints as defined in ISO/IEC TR 23188:2020
              items:
                type: string
                minItems: 1
          required:
            - maintainedBy
            - hostedOn
            - tenantOwnedBy
            - endpoint
security:
  - bearerAuth: []         # use the same name as above