apiVersion: v1
kind: Secret
metadata:
  name: avp-sdfactory-secret
type: Opaque
stringData:
  ClientID: {{ .Values.sdfactory.secret.clientId }}
  ClientSecret: {{ .Values.sdfactory.secret.clientSecret }}
