apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.issuer }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~* "http.?:\/\/(.*\.)?(localhost:3000|catena-x\.net|example\.com|idses-fe\.demo\.catena-x\.net).*$") {
        set $allow_origin $http_origin
      }

      more_set_headers "Access-Control-Allow-Origin" "$http_origin" always;
      more_set_headers "Access-Control-Allow-Methods" "GET, PUT, POST, OPTIONS, DELETE" always;
      more_set_headers "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
      more_set_headers "Access-Control-Expose-Headers" "Content-Range";

      if ($request_method = 'OPTIONS') {
        more_set_headers 'Access-Control-Max-Age: 1728000';
        more_set_headers 'Content-Type: text/plain charset=UTF-8';
        more_set_headers 'Content-Length: 0';
        return 204;
      }
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.name }}.{{ .Values.domain }}-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.portService }}
