image: "ghcr.io/catenax-ng/product-sd-hub/sdfactory:latest"
domain: "sdfactory.int.demo.catena-x.net"
name: "sdfactory"
portContainer: 8080
portService: 80
replicaCount: 1
issuer: "letsencrypt-prod"
#namespace: product-essential-services
