ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - domain: "sdfactory.int.demo.catena-x.net"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
