apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  dbuser: "<path:essential-services/data/postgres#DB_USER>"
  postgres-password: "<path:essential-services/data/postgres#DB_PASS>"
  password: "<path:essential-services/data/postgres#DB_PASS>"
