# This is a basic workflow to help you get started with Actions

name: SDFactory Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  ACR_NAME: catenaxdev001acr.azurecr.io
  version: 0.1.0
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    - name: Clone public product-sd-hub PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v1
      with:
       owner: 'Catena-X (ng)'
       repository: 'product-sd-hub'
     
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        login-server: ${{ env.ACR_NAME }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
    - name: Building and pusing docker image to acr
      run: |
        cd SDFactory && docker build -f Dockerfile -t ${{ env.ACR_NAME }}/SDFactory:latest .
        docker push ${{ env.ACR_NAME }}/SDFactory:latest 
